### ISSUE TITLE
User Auth MVP

### ISSUE THREAD

**Issue by andywynkoop** [johnenriquez/spacebrite#1]
Hey John, here are a few things I think you'll need to do to finish the User Auth MVP. Great job so far!
## Splash Page
- [x] I think this looks really good, nice work!
- [x] I think you can omit the footer links if you want to, especially if they don't do anything

## Sign Up / Log In
- [x] I am currently unable to login or sign up, I'm seeing an error about `e.map` not being a function

## Todos
- [x] Address above issue, then let me know!

**Comment by johnenriquez** [comment]
received the `:dank:` emoji as confirmation, therefore closing

**Comment by andywynkoop** [comment]
A few last suggestions:
- [ ] Errors should clear when switching between login + sign up
- [ ] Going to a random route, like `/space/something` should redirect to `/` or render a 404 page
- [ ] Add a demo user
